_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 15
                - 16
                - 19
                - 23
                - 47
                - 55
            "4": 3.12.10
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
augmentations:
    value:
        degrees: 5
        erasing: 0.5
        fliplr: 0
        hsv_s: 0.7
        mosaic: 0
        scale: 0.5
        shear: 0.1
batch:
    value: 64
data:
    value: /home/sahithi_kukkala/indicDLP/data/indic_data/data.yaml
device:
    value: "4"
imgsz:
    value: 1024
model:
    value: yolov10x
patience:
    value: 5
train:
    value:
        agnostic_nms: false
        amp: true
        augment: false
        auto_augment: randaugment
        batch: 64
        bgr: 0
        box: 7.5
        cache: false
        cfg: null
        classes: null
        close_mosaic: 10
        cls: 0.5
        conf: null
        copy_paste: 0
        copy_paste_mode: flip
        cos_lr: false
        cutmix: 0
        data: /home/sahithi_kukkala/indicDLP/data/indic_data/data.yaml
        degrees: 5
        deterministic: true
        device: "4"
        dfl: 1.5
        dnn: false
        dropout: 0
        dynamic: false
        embed: null
        epochs: 100
        erasing: 0.5
        exist_ok: false
        fliplr: 0
        flipud: 0
        format: torchscript
        fraction: 1
        freeze: null
        half: false
        hsv_h: 0.015
        hsv_s: 0.7
        hsv_v: 0.4
        imgsz: 1024
        int8: false
        iou: 0.7
        keras: false
        kobj: 1
        line_width: null
        lr0: 0.01
        lrf: 0.01
        mask_ratio: 4
        max_det: 300
        mixup: 0
        mode: train
        model: yolov10x.yaml
        momentum: 0.937
        mosaic: 0
        multi_scale: false
        name: YOLOv10x-1024imgsz-AugScratch3
        nbs: 64
        nms: false
        opset: null
        optimize: false
        optimizer: auto
        overlap_mask: true
        patience: 5
        perspective: 0
        plots: true
        pose: 12
        pretrained: true
        profile: false
        project: yolov10_scratch_indic
        rect: false
        resume: false
        retina_masks: false
        save: true
        save_conf: false
        save_crop: false
        save_dir: yolov10_scratch_indic/YOLOv10x-1024imgsz-AugScratch3
        save_frames: false
        save_json: false
        save_period: -1
        save_txt: false
        scale: 0.5
        seed: 0
        shear: 0.1
        show: false
        show_boxes: true
        show_conf: true
        show_labels: true
        simplify: true
        single_cls: false
        source: null
        split: val
        stream_buffer: false
        task: detect
        time: null
        tracker: botsort.yaml
        translate: 0.1
        val: true
        verbose: true
        vid_stride: 1
        visualize: false
        warmup_bias_lr: 0
        warmup_epochs: 3
        warmup_momentum: 0.8
        weight_decay: 0.0005
        workers: 8
        workspace: null
